# Generated by Django 4.2.5 on 2024-10-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.FloatField()),
                ('debit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UtilisationEau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.CharField(max_length=100)),
                ('quantite_utilisee', models.FloatField()),
                ('date', models.DateField()),
                ('source_eau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='water_management.sourceeau')),
            ],
        ),
    ]
