# Generated by Django 5.1.2 on 2024-10-29 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('composition', models.TextField(verbose_name='Composition chimique')),
                ('type_pesticide', models.CharField(choices=[('HERBICIDE', 'Herbicide'), ('INSECTICIDE', 'Insecticide'), ('FONGICIDE', 'Fongicide'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de pesticide')),
                ('type_culture', models.CharField(choices=[('CEREALES', 'Céréales'), ('LEGUMES', 'Légumes'), ('FRUITS', 'Fruits'), ('VIGNE', 'Vigne'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de culture')),
                ('dose_recommandee', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dose recommandée (L/ha)')),
                ('delai_reentree', models.IntegerField(help_text='Délai minimum avant de pouvoir retourner sur la parcelle', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Délai de réentrée (heures)')),
            ],
            options={
                'verbose_name': 'Pesticide',
                'verbose_name_plural': 'Pesticides',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.CharField(help_text='Nom ou numéro de la parcelle', max_length=100, verbose_name='Parcelle')),
                ('surface_traitee', models.FloatField(help_text='Surface de la parcelle traitée en hectares', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface traitée (ha)')),
                ('quantite', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité (L)')),
                ('date_application', models.DateField(verbose_name="Date d'application")),
                ('conditions_meteo', models.TextField(blank=True, help_text='Température, vent, humidité...', verbose_name='Conditions météorologiques')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm', verbose_name='Exploitation agricole')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesticides.pesticide', verbose_name='Pesticide')),
            ],
            options={
                'verbose_name': 'Application de pesticide',
                'verbose_name_plural': 'Applications de pesticides',
                'ordering': ['-date_application'],
            },
        ),
    ]
