# Generated by Django 5.1.2 on 2024-10-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='parcelle',
        ),
        migrations.RemoveField(
            model_name='application',
            name='surface_traitee',
        ),
    ]
