# Generated by Django 5.1.2 on 2024-10-29 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEngrais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationengrais',
            options={'ordering': ['-date'], 'verbose_name': "Application d'engrais", 'verbose_name_plural': "Applications d'engrais"},
        ),
        migrations.AlterModelOptions(
            name='engrais',
            options={'verbose_name': 'Engrais', 'verbose_name_plural': 'Engrais'},
        ),
        migrations.AlterField(
            model_name='applicationengrais',
            name='ia',
            field=models.TextField(verbose_name='AI Optimization'),
        ),
        migrations.AlterField(
            model_name='applicationengrais',
            name='quantite',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='engrais',
            name='recommandation_dose',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
