# Generated by Django 5.1.2 on 2024-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEngrais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationengrais',
            old_name='IA',
            new_name='ia',
        ),
        migrations.AlterField(
            model_name='engrais',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
