# Generated by Django 4.2.5 on 2024-10-30 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEngrais', '0004_remove_applicationengrais_ia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationengrais',
            name='analyse_sol',
        ),
        migrations.RemoveField(
            model_name='applicationengrais',
            name='conditions_meteo',
        ),
        migrations.RemoveField(
            model_name='applicationengrais',
            name='historique_applications',
        ),
        migrations.RemoveField(
            model_name='applicationengrais',
            name='recommandations_ia',
        ),
        migrations.AlterField(
            model_name='engrais',
            name='recommandation_dose',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
