# Generated by Django 5.1.2 on 2024-10-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('GRAIN', 'Grain'), ('OTHER', 'Other')], max_length=20)),
                ('growth_stage', models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGETATIVE', 'Vegetative'), ('FLOWERING', 'Flowering'), ('FRUITING', 'Fruiting'), ('MATURE', 'Mature')], default='SEEDLING', max_length=20)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in hectares', max_digits=10)),
                ('water_requirements', models.DecimalField(decimal_places=2, help_text='Water needed in L/day', max_digits=10)),
                ('fertilizer_requirements', models.DecimalField(decimal_places=2, help_text='Fertilizer needed in kg/ha', max_digits=10)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('health', models.IntegerField(default=100, help_text='Crop health percentage')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farms.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
