# Generated by Django 5.1.2 on 2024-10-29 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dechets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedechet',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typedechet',
            name='efficacite_traitement',
            field=models.IntegerField(default=75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='typedechet',
            name='biodegradable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='typedechet',
            name='methode_traitement',
            field=models.CharField(choices=[('COMPOST', 'Compostage'), ('RECYCLAGE', 'Recyclage'), ('INCINERATION', 'Incinération'), ('ENFOUISSEMENT', 'Enfouissement')], default='COMPOST', max_length=20),
        ),
        migrations.AlterField(
            model_name='typedechet',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
